"""
LSTM-based Insider Threat / Anomaly Detection — Training Script
================================================================
Expects data generated by generate_sessions.py at data/raw/synthetic_commands.parquet

Label schema:
  0 = benign
  1 = suspicious
  2 = malicious

Key improvements over baseline:
  - 3-class output (not binary)
  - Correct file path (data/raw/)
  - Dynamic max_len capped at 60 to capture full attack chains
  - Class-weighted CrossEntropyLoss to handle 68/23/9 imbalance
  - Metadata features: after_hours, command_count, sudo_count, unique_cmd_ratio
  - LSTMRiskModel fuses sequence hidden state + metadata before classification
  - Proper train / val / test three-way split
  - Validation loss tracked each epoch with early stopping
  - Per-class F1 reported at evaluation
"""

import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_recall_curve,
    average_precision_score,
)
from sklearn.preprocessing import StandardScaler
import matplotlib
matplotlib.use("Agg")          # non-interactive — safe on all platforms
import matplotlib.pyplot as plt


# CONFIG

DATA_PATH   = "data/raw/synthetic_commands.parquet"
BATCH_SIZE  = 64
EPOCHS      = 15
LR          = 5e-4          
EMBED_DIM   = 128        
HIDDEN_DIM  = 256        
PATIENCE    = 3
SEED        = 42
NUM_CLASSES = 3

torch.manual_seed(SEED)
np.random.seed(SEED)



# TOKENIZER

class CommandTokenizer:
    """
    Converts raw bash command strings into padded integer sequences.
    Vocabulary is built from training data only to prevent leakage.
    """
    def __init__(self, max_len=60):
        self.max_len = max_len
        self.vocab   = {"<PAD>": 0, "<UNK>": 1}
        self.idx     = 2

    def fit(self, sequences):
        for seq in sequences:
            for cmd in seq.split(" -> "):
                if cmd not in self.vocab:
                    self.vocab[cmd] = self.idx
                    self.idx += 1

    def transform(self, sequences):
        encoded = []
        for seq in sequences:
            cmds = seq.split(" -> ")
            # Keep the TAIL so attack chain commands (usually appended) are preserved
            if len(cmds) > self.max_len:
                cmds = cmds[-self.max_len:]
            ids        = [self.vocab.get(cmd, 1) for cmd in cmds]
            pad_length = self.max_len - len(ids)
            ids        = [0] * pad_length + ids
            encoded.append(ids)
        return np.array(encoded, dtype=np.int64)

    def fit_transform(self, sequences):
        self.fit(sequences)
        return self.transform(sequences)



# METADATA FEATURE EXTRACTION

def extract_meta_features(df: pd.DataFrame) -> np.ndarray:
    """
    Derives numeric features from session metadata.
    All features are scaled later via StandardScaler (fit on train only).
    """
    feats = pd.DataFrame()

    feats["after_hours"]   = df["after_hours"].astype(float)
    feats["command_count"] = df["command_count"].astype(float)

    # Fraction of unique commands in the session (low = repetitive / scripted)
    def unique_ratio(seq):
        cmds = seq.split(" -> ")
        return len(set(cmds)) / max(len(cmds), 1)

    feats["unique_cmd_ratio"] = df["command_sequence"].apply(unique_ratio)

    # Count sudo invocations — strong signal for privilege activity
    feats["sudo_count"] = df["command_sequence"].str.count(r"\bsudo\b")

    # Count suspicious keywords
    feats["suspicious_kw"] = df["command_sequence"].str.count(
        r"(base64|wget|curl|scp|nmap|sshpass|chmod 777|crontab|/etc/shadow|/etc/passwd|attacker)"
    )

    # Session duration (if available)
    feats["session_duration_s"] = df["session_duration_s"].astype(float)

    return feats.values.astype(np.float32)



# DATASET

class SequenceDataset(Dataset):
    def __init__(self, X_seq, X_meta, y):
        self.X_seq  = torch.tensor(X_seq,  dtype=torch.long)
        self.X_meta = torch.tensor(X_meta, dtype=torch.float)
        self.y      = torch.tensor(y,      dtype=torch.long)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X_seq[idx], self.X_meta[idx], self.y[idx]



# MODEL

class LSTMRiskModel(nn.Module):
    """
    Embedding → BiLSTM → concat metadata → dropout → FC classifier

    Using a bidirectional LSTM so the model can attend to both early
    (role-establishment) and late (attack chain) parts of a session.
    The final hidden state is concatenated with numeric metadata features
    before the classification head.
    """
    def __init__(self, vocab_size, embed_dim=64, hidden_dim=128,
                 num_meta=6, num_classes=3, dropout=0.3):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)

        self.lstm = nn.LSTM(
            embed_dim, hidden_dim,
            batch_first=True,
            bidirectional=True,
            num_layers=2,
            dropout=dropout
        )

        # BiLSTM outputs hidden_dim * 2
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim * 2 + num_meta, num_classes)

    def forward(self, x_seq, x_meta):
        emb         = self.embedding(x_seq)              # (B, T, E)
        out, _      = self.lstm(emb)                     # (B, T, H*2)
        last_hidden = out[:, -1, :]                      # (B, H*2)
        fused       = torch.cat([last_hidden, x_meta], dim=1)  # (B, H*2 + num_meta)
        fused       = self.dropout(fused)
        return self.fc(fused)                            # (B, num_classes)



# TRAINING HELPERS


def run_epoch(model, loader, criterion, optimizer, device, train=True):
    model.train() if train else model.eval()
    total_loss, correct, total = 0.0, 0, 0

    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for x_seq, x_meta, y in loader:
            x_seq, x_meta, y = x_seq.to(device), x_meta.to(device), y.to(device)

            if train:
                optimizer.zero_grad()

            outputs = model(x_seq, x_meta)
            loss    = criterion(outputs, y)

            if train:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
                optimizer.step()

            total_loss += loss.item()
            preds       = outputs.argmax(dim=1)
            correct    += (preds == y).sum().item()
            total      += y.size(0)

    return total_loss / len(loader), correct / total


def evaluate(model, loader, device):
    """Return argmax predictions, raw class probabilities, and true targets."""
    model.eval()
    all_probs, all_preds, all_targets = [], [], []
    with torch.no_grad():
        for x_seq, x_meta, y in loader:
            x_seq, x_meta = x_seq.to(device), x_meta.to(device)
            logits  = model(x_seq, x_meta)
            probs   = torch.softmax(logits, dim=1).cpu().numpy()
            preds   = logits.argmax(dim=1).cpu().numpy()
            all_probs.extend(probs)
            all_preds.extend(preds)
            all_targets.extend(y.numpy())
    return np.array(all_preds), np.array(all_targets), np.array(all_probs)



# MAIN


def train_model():
    print("=" * 60)
    print("  Insider Threat LSTM — Training Pipeline")
    print("=" * 60)

    # ── 1. Load data
    print(f"\n[1/7] Loading data from {DATA_PATH} ...")
    df = pd.read_parquet(DATA_PATH)
    print(f"      Loaded {len(df):,} sessions")
    print(f"      Label distribution:\n{df['label'].value_counts().sort_index().to_string()}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[2/7] Device: {device}")

    # ── 2. Sequence length analysis
    seq_lengths  = df["command_sequence"].str.split(" -> ").str.len()
    max_observed = int(seq_lengths.max())
    print(f"\n[3/7] Sequence stats — max: {max_observed}, avg: {seq_lengths.mean():.1f}, "
          f"p95: {seq_lengths.quantile(0.95):.0f}")
    max_len = min(max_observed, 60)
    print(f"      Using max_len = {max_len}")

    # ── 3. Three-way stratified split BEFORE fitting tokenizer/scaler
    sequences = df["command_sequence"].tolist()
    labels    = df["label"].tolist()
    meta_raw  = extract_meta_features(df)

    X_train_seq, X_temp_seq, y_train, y_temp, \
    X_train_meta, X_temp_meta = train_test_split(
        sequences, labels, meta_raw,
        test_size=0.30, random_state=SEED, stratify=labels
    )
    X_val_seq, X_test_seq, y_val, y_test, \
    X_val_meta, X_test_meta = train_test_split(
        X_temp_seq, y_temp, X_temp_meta,
        test_size=0.50, random_state=SEED, stratify=y_temp
    )
    print(f"\n      Split → train: {len(y_train):,} | val: {len(y_val):,} | test: {len(y_test):,}")

    # ── 4. Tokenize
    print("\n[4/7] Tokenizing sequences ...")
    tokenizer      = CommandTokenizer(max_len=max_len)
    X_train_seq_enc = tokenizer.fit_transform(X_train_seq)
    X_val_seq_enc   = tokenizer.transform(X_val_seq)
    X_test_seq_enc  = tokenizer.transform(X_test_seq)
    vocab_size      = len(tokenizer.vocab)
    print(f"      Vocabulary size: {vocab_size:,}")

    # ── 5. Scale metadata 
    scaler         = StandardScaler()
    X_train_meta_s = scaler.fit_transform(X_train_meta)
    X_val_meta_s   = scaler.transform(X_val_meta)
    X_test_meta_s  = scaler.transform(X_test_meta)
    num_meta       = X_train_meta_s.shape[1]

    # ── 6. DataLoaders
    train_loader = DataLoader(
        SequenceDataset(X_train_seq_enc, X_train_meta_s, y_train),
        batch_size=BATCH_SIZE, shuffle=True,  num_workers=0
    )
    val_loader = DataLoader(
        SequenceDataset(X_val_seq_enc, X_val_meta_s, y_val),
        batch_size=BATCH_SIZE, shuffle=False, num_workers=0
    )
    test_loader = DataLoader(
        SequenceDataset(X_test_seq_enc, X_test_meta_s, y_test),
        batch_size=BATCH_SIZE, shuffle=False, num_workers=0
    )

    # ── 7. Class-weighted loss
    counts       = np.bincount(y_train, minlength=NUM_CLASSES).astype(np.float32)
    class_weights = torch.tensor(1.0 / counts, dtype=torch.float).to(device)
    class_weights = class_weights / class_weights.sum() * NUM_CLASSES  # normalize
    criterion    = nn.CrossEntropyLoss(weight=class_weights)

    # ── 8. Model, optimizer, scheduler
    print(f"\n[5/7] Building model (vocab={vocab_size}, meta_features={num_meta}) ...")
    model     = LSTMRiskModel(
        vocab_size=vocab_size,
        embed_dim=EMBED_DIM,
        hidden_dim=HIDDEN_DIM,
        num_meta=num_meta,
        num_classes=NUM_CLASSES
    ).to(device)

    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"      Trainable parameters: {total_params:,}")

    optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=2
    )

    # ── 9. Training loop with early stopping
    print(f"\n[6/7] Training for up to {EPOCHS} epochs (early stopping patience={PATIENCE}) ...")
    print("-" * 60)

    best_val_loss  = float("inf")
    patience_count = 0
    best_state     = None

    for epoch in range(1, EPOCHS + 1):
        train_loss, train_acc = run_epoch(model, train_loader, criterion, optimizer, device, train=True)
        val_loss,   val_acc   = run_epoch(model, val_loader,   criterion, optimizer, device, train=False)
        scheduler.step(val_loss)

        flag = ""
        if val_loss < best_val_loss:
            best_val_loss  = val_loss
            best_state     = {k: v.clone() for k, v in model.state_dict().items()}
            patience_count = 0
            flag = "  ✓ best"
        else:
            patience_count += 1
            flag = f"  (patience {patience_count}/{PATIENCE})"

        print(f"  Epoch {epoch:02d}/{EPOCHS} | "
              f"train loss: {train_loss:.4f}, acc: {train_acc:.3f} | "
              f"val loss: {val_loss:.4f}, acc: {val_acc:.3f}{flag}")

        if patience_count >= PATIENCE:
            print(f"\n  Early stopping triggered at epoch {epoch}.")
            break

    # ── 10. Evaluate best model on test set
    print(f"\n[7/7] Evaluating best model on held-out test set ...")
    print("-" * 60)
    model.load_state_dict(best_state)
    preds, targets, probs = evaluate(model, test_loader, device)

    # ── 10a. Standard argmax classification report
    print("\nClassification Report (argmax threshold = 0.50):")
    print(classification_report(
        targets, preds,
        target_names=["Benign (0)", "Suspicious (1)", "Malicious (2)"],
        digits=4
    ))

    # ── 10b. Confusion matrix
    cm = confusion_matrix(targets, preds)
    print("Confusion Matrix (rows=true, cols=pred):")
    print(f"  {'':>16}  {'Benign':>8}  {'Suspic.':>8}  {'Malicious':>10}")
    for i, row_name in enumerate(["Benign", "Suspicious", "Malicious"]):
        print(f"  {row_name:>16}  {cm[i,0]:>8}  {cm[i,1]:>8}  {cm[i,2]:>10}")

    # ── 10c. Miss breakdown by attack_type (malicious sessions only)
    # Recover test indices by rerunning the same splits with the same seed
    all_idx = np.arange(len(df))
    _, idx_temp = train_test_split(
        all_idx, test_size=0.30, random_state=SEED,
        stratify=df["label"].tolist()
    )
    _, idx_test_final = train_test_split(
        idx_temp, test_size=0.50, random_state=SEED,
        stratify=df["label"].iloc[idx_temp].tolist()
    )
    test_attack = df["attack_type"].iloc[idx_test_final].values

    missed_mask  = (targets == 2) & (preds != 2)
    if missed_mask.sum() > 0:
        missed_types = pd.Series(test_attack[missed_mask])
        print(f"\nMalicious miss breakdown by attack_type "
              f"({missed_mask.sum()} total misses):")
        print(missed_types.value_counts().to_string())
    else:
        print("\nNo malicious sessions missed — perfect malicious recall.")

    # ── 10d. Threshold sweep on malicious class
    #         Find the threshold where malicious recall crosses key targets
    mal_probs   = probs[:, 2]          # P(malicious) for every test session
    is_mal_true = (targets == 2).astype(int)

    prec_curve, rec_curve, thresh_curve = precision_recall_curve(
        is_mal_true, mal_probs
    )
    ap_score = average_precision_score(is_mal_true, mal_probs)

    print(f"\nMalicious class — Average Precision (AP): {ap_score:.4f}")
    print(f"\nThreshold sweep  (malicious P(x)≥t → predict malicious):")
    print(f"  {'Threshold':>10}  {'Precision':>10}  {'Recall':>8}  {'F1':>8}  {'Flagged%':>9}")
    print(f"  {'─'*52}")

    chosen_thresh = 0.50   # default, updated below
    chosen_rec    = 0.0

    for t in [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.60, 0.70]:
        swept_preds        = preds.copy()
        swept_preds[mal_probs >= t] = 2
        mal_mask           = swept_preds == 2
        tp = ((swept_preds == 2) & (targets == 2)).sum()
        fp = ((swept_preds == 2) & (targets != 2)).sum()
        fn = ((swept_preds != 2) & (targets == 2)).sum()
        p  = tp / (tp + fp + 1e-9)
        r  = tp / (tp + fn + 1e-9)
        f1 = 2 * p * r / (p + r + 1e-9)
        flagged_pct = mal_mask.mean() * 100
        marker = ""
        # Auto-select threshold: highest recall while precision >= 0.85
        if p >= 0.85 and r > chosen_rec:
            chosen_thresh = t
            chosen_rec    = r
            marker = "  ← selected"
        print(f"  {t:>10.2f}  {p:>10.4f}  {r:>8.4f}  {f1:>8.4f}  {flagged_pct:>8.1f}%{marker}")

    print(f"\n  Operating point: threshold = {chosen_thresh:.2f}  "
          f"(recall = {chosen_rec:.4f}, precision ≥ 0.85)")

    # ── 10e. Final report at chosen threshold
    final_preds = preds.copy()
    final_preds[mal_probs >= chosen_thresh] = 2
    print(f"\nClassification Report at chosen threshold ({chosen_thresh:.2f}):")
    print(classification_report(
        targets, final_preds,
        target_names=["Benign (0)", "Suspicious (1)", "Malicious (2)"],
        digits=4
    ))

    # ── 10f. Precision-Recall curve plot
    Path("models").mkdir(exist_ok=True)
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # PR curve
    axes[0].plot(rec_curve, prec_curve, lw=2, color="#2563EB", label=f"AP = {ap_score:.3f}")
    axes[0].axvline(chosen_rec,  color="#DC2626", ls="--", lw=1.2, label=f"thresh={chosen_thresh:.2f}")
    axes[0].set_xlabel("Recall",    fontsize=12)
    axes[0].set_ylabel("Precision", fontsize=12)
    axes[0].set_title("Malicious Class — Precision-Recall Curve", fontsize=13, fontweight="bold")
    axes[0].legend(fontsize=10)
    axes[0].set_xlim([0, 1]); axes[0].set_ylim([0, 1.02])
    axes[0].grid(alpha=0.3)

    # Confusion matrix heatmap at chosen threshold
    cm_final = confusion_matrix(targets, final_preds)
    labels   = ["Benign", "Suspicious", "Malicious"]
    im = axes[1].imshow(cm_final, cmap="Blues")
    axes[1].set_xticks(range(3)); axes[1].set_yticks(range(3))
    axes[1].set_xticklabels(labels, fontsize=10)
    axes[1].set_yticklabels(labels, fontsize=10, rotation=45, ha="right")
    axes[1].set_xlabel("Predicted", fontsize=12)
    axes[1].set_ylabel("True",      fontsize=12)
    axes[1].set_title(f"Confusion Matrix (thresh={chosen_thresh:.2f})", fontsize=13, fontweight="bold")
    for i in range(3):
        for j in range(3):
            val   = cm_final[i, j]
            color = "white" if val > cm_final.max() / 2 else "black"
            axes[1].text(j, i, str(val), ha="center", va="center",
                         fontsize=14, fontweight="bold", color=color)
    plt.colorbar(im, ax=axes[1])
    plt.tight_layout()
    plot_path = "models/pr_curve_and_cm.png"
    plt.savefig(plot_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"\nPR curve + confusion matrix saved → {plot_path}")

    # ── 11. Save model + tokenizer vocab + chosen threshold
    torch.save({
        "model_state":    best_state,
        "vocab":          tokenizer.vocab,
        "scaler_mean":    scaler.mean_,
        "scaler_scale":   scaler.scale_,
        "max_len":        max_len,
        "num_meta":       num_meta,
        "num_classes":    NUM_CLASSES,
        "embed_dim":      EMBED_DIM,
        "hidden_dim":     HIDDEN_DIM,
        "mal_threshold":  chosen_thresh,   # load this at inference time
    }, "models/lstm_risk_model.pt")
    print(f"Model saved → models/lstm_risk_model.pt")
    print("=" * 60)


if __name__ == "__main__":
    train_model()